package com.dlohaiti.dlokiosk;

public enum Measurements {
    TEMPERATURE,
    PH,
    TURBIDITY,
    TDS,
    FREE_CHLORINE_CONCENTRATION,
    TOTAL_CHLORINE_CONCENTRATION,
    FREE_CHLORINE_RESIDUAL,
    TOTAL_CHLORINE_RESIDUAL,
    ALKALINITY,
    HARDNESS,
    COLOR,
    ODOR,
    TASTE
}
